/*
 * reed_solomon.c - Reed-Solomon code over GF(2^8).
 *
 * RS works on SYMBOLS (here, bytes) drawn from a finite field. A
 * corrupted symbol counts as a single error no matter how many of its
 * 8 bits flipped, which is why RS is so strong against burst errors.
 *
 * RS(n, k) with nroots = n - k = 2t parity symbols corrects up to t
 * symbol errors. Decoding here uses the classic pipeline:
 *   syndromes -> Berlekamp-Massey -> Chien search -> Forney algorithm.
 *
 * The field is GF(2^8) generated by the primitive polynomial
 * 0x11D (x^8 + x^4 + x^3 + x^2 + 1), the standard choice used by the
 * CCSDS / DVB / QR-code RS codes.
 */
#include "coding/correct.h"

#define GF 256
#define PRIM 0x11D            /* primitive polynomial for GF(2^8) */

static uint8_t gf_exp[2 * GF]; /* antilog table (doubled to skip %)  */
static uint8_t gf_log[GF];     /* log table                          */
static int     gf_ready = 0;

/* Build the exp/log tables for GF(2^8). */
static void gf_init(void) {
    int x = 1;
    for (int i = 0; i < GF - 1; ++i) {
        gf_exp[i] = (uint8_t)x;
        gf_log[x] = (uint8_t)i;
        x <<= 1;
        if (x & GF)
            x ^= PRIM;       /* reduce modulo the primitive poly */
    }
    /* Duplicate so gf_exp[i + j] is valid for i, j < 255. */
    for (int i = GF - 1; i < 2 * GF; ++i)
        gf_exp[i] = gf_exp[i - (GF - 1)];
    gf_ready = 1;
}

/* Field multiply. */
static uint8_t gf_mul(uint8_t a, uint8_t b) {
    if (a == 0 || b == 0) return 0;
    return gf_exp[gf_log[a] + gf_log[b]];
}

/* Field inverse of a (used via gf_div; kept inline-friendly). */
static uint8_t gf_inv(uint8_t a) {
    return gf_exp[(GF - 1) - gf_log[a]];
}

/* a divided by b. */
static uint8_t gf_div(uint8_t a, uint8_t b) {
    if (a == 0) return 0;
    return gf_mul(a, gf_inv(b));
}

/* alpha raised to power p. */
static uint8_t gf_pow_alpha(int p) {
    p %= (GF - 1);
    if (p < 0) p += (GF - 1);
    return gf_exp[p];
}

int dsp_rs_init(dsp_rs *rs, int nroots) {
    if (nroots <= 0 || nroots >= GF - 1 || (nroots & 1))
        return -1;
    if (!gf_ready)
        gf_init();

    rs->nroots = nroots;

    /* Generator polynomial g(x) = prod_{i=0}^{nroots-1} (x - alpha^i). */
    uint8_t *g = rs->gen;
    for (int i = 0; i <= nroots; ++i)
        g[i] = 0;
    g[0] = 1;
    int deg = 0;
    for (int i = 0; i < nroots; ++i) {
        uint8_t root = gf_pow_alpha(i);
        /* Multiply g(x) by (x - root). */
        for (int j = deg + 1; j > 0; --j)
            g[j] = g[j - 1] ^ gf_mul(g[j], root);
        g[0] = gf_mul(g[0], root);
        ++deg;
    }
    return 0;
}

void dsp_rs_encode(const dsp_rs *rs, const uint8_t *data, size_t k,
                   uint8_t *parity) {
    int nr = rs->nroots;
    for (int i = 0; i < nr; ++i)
        parity[i] = 0;

    /* Systematic encoding: polynomial division of the message
     * (shifted up by nroots) by the generator; remainder is parity. */
    for (size_t i = 0; i < k; ++i) {
        uint8_t feedback = data[i] ^ parity[0];
        for (int j = 0; j < nr - 1; ++j)
            parity[j] = parity[j + 1]
                      ^ gf_mul(feedback, rs->gen[nr - 1 - j]);
        parity[nr - 1] = gf_mul(feedback, rs->gen[0]);
    }
}

int dsp_rs_decode(const dsp_rs *rs, uint8_t *code, size_t n) {
    int nr = rs->nroots;
    int t  = nr / 2;

    /* --- 1. Syndromes: evaluate the received polynomial at alpha^i. */
    uint8_t synd[DSP_RS_NN];
    int errors_present = 0;
    for (int i = 0; i < nr; ++i) {
        uint8_t s = 0;
        uint8_t xi = gf_pow_alpha(i);
        for (size_t j = 0; j < n; ++j)
            s = code[j] ^ gf_mul(s, xi);
        synd[i] = s;
        if (s != 0) errors_present = 1;
    }
    if (!errors_present)
        return 0;                  /* clean codeword */

    /* --- 2. Berlekamp-Massey: find the error-locator polynomial. */
    uint8_t lambda[DSP_RS_NN] = {1};
    uint8_t prev[DSP_RS_NN]   = {1};
    uint8_t tmp[DSP_RS_NN];
    int L = 0;                     /* current locator degree */
    int m = 1;
    uint8_t b = 1;

    for (int r = 0; r < nr; ++r) {
        /* Discrepancy. */
        uint8_t delta = synd[r];
        for (int i = 1; i <= L; ++i)
            delta ^= gf_mul(lambda[i], synd[r - i]);

        if (delta == 0) {
            ++m;
        } else if (2 * L <= r) {
            for (int i = 0; i < DSP_RS_NN; ++i) tmp[i] = lambda[i];
            uint8_t coef = gf_div(delta, b);
            for (int i = 0; i + m < DSP_RS_NN; ++i)
                lambda[i + m] ^= gf_mul(coef, prev[i]);
            L = r + 1 - L;
            for (int i = 0; i < DSP_RS_NN; ++i) prev[i] = tmp[i];
            b = delta;
            m = 1;
        } else {
            uint8_t coef = gf_div(delta, b);
            for (int i = 0; i + m < DSP_RS_NN; ++i)
                lambda[i + m] ^= gf_mul(coef, prev[i]);
            ++m;
        }
    }

    if (L > t)
        return -1;                 /* too many errors to correct */

    /* --- 3. Chien search: roots of lambda give error locations. */
    int    err_pos[DSP_RS_NN];
    int    nerr = 0;
    for (int i = 0; i < (int)n; ++i) {
        /* Evaluate lambda at alpha^-i. */
        uint8_t sum = 0;
        for (int j = 0; j <= L; ++j)
            sum ^= gf_mul(lambda[j], gf_pow_alpha(-i * j));
        if (sum == 0) {
            /* Position index within the codeword. */
            err_pos[nerr++] = (int)n - 1 - i;
        }
    }
    if (nerr != L)
        return -1;                 /* locator inconsistent -> fail */

    /* --- 4. Forney algorithm: compute error magnitudes. */
    /* Error evaluator omega(x) = S(x) * lambda(x) mod x^nroots. */
    uint8_t omega[DSP_RS_NN] = {0};
    for (int i = 0; i < nr; ++i) {
        uint8_t s = 0;
        for (int j = 0; j <= i; ++j)
            s ^= gf_mul(synd[i - j], lambda[j]);
        omega[i] = s;
    }

    for (int e = 0; e < nerr; ++e) {
        int pos = err_pos[e];
        int i   = (int)n - 1 - pos;          /* power of x at this error */

        /* Error locator value X_k = alpha^i, and its inverse. */
        uint8_t xinv = gf_pow_alpha(-i);     /* X_k^-1 */

        /* Numerator: omega(X_k^-1). */
        uint8_t num = 0;
        for (int j = 0; j < nr; ++j)
            num ^= gf_mul(omega[j], gf_pow_alpha(-i * j));

        /* Denominator: lambda'(X_k^-1). The formal derivative over
         * GF(2) keeps only odd-degree terms (even terms differentiate
         * to zero), and term j contributes lambda[j] * x^(j-1). */
        uint8_t den = 0;
        for (int j = 1; j <= L; j += 2)
            den ^= gf_mul(lambda[j], gf_pow_alpha(-i * (j - 1)));

        if (den == 0)
            return -1;

        /* Forney: e_k = X_k * omega(X_k^-1) / lambda'(X_k^-1).
         * With syndromes indexed from S_0, X_k = alpha^i multiplies. */
        uint8_t mag = gf_mul(gf_pow_alpha(i), gf_div(num, den));
        code[pos] ^= mag;                    /* repair the symbol */
        (void)xinv;
    }

    return nerr;
}
